version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo "Current directory before cd:"
      - pwd
      - echo "Listing files in current directory:"
      - ls -la
      - echo "Checking EFS mount point:"
      - ls -la /mnt/repos
      - cd /mnt/repos/Adelkazzaz/flask-test-deploy
      - echo "Current directory after cd:"
      - pwd
      - echo "Listing files in repository directory:"
      - ls -la
      - docker --version || echo "Docker not installed!"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 058264170818.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=058264170818.dkr.ecr.us-east-1.amazonaws.com/flask-test-deploy-119636436
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Building the Docker image...
      - echo "Current directory for build:"
      - pwd
      - echo "Listing files in current directory:"
      - ls -la
      - docker build -t 058264170818.dkr.ecr.us-east-1.amazonaws.com/flask-test-deploy-119636436:latest --build-arg PORT=$PORT --build-arg ENTRY_POINT=$ENTRY_POINT -f Dockerfile .
      - docker tag 058264170818.dkr.ecr.us-east-1.amazonaws.com/flask-test-deploy-119636436:latest 058264170818.dkr.ecr.us-east-1.amazonaws.com/flask-test-deploy-119636436:latest
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push 058264170818.dkr.ecr.us-east-1.amazonaws.com/flask-test-deploy-119636436:latest
      - echo Writing image definitions file...
      - cd $CODEBUILD_SRC_DIR
      - printf '{"ImageURI":"%s"}' "058264170818.dkr.ecr.us-east-1.amazonaws.com/flask-test-deploy-119636436:latest" > imageDetail.json
      - cat imageDetail.json
      - echo "Current directory for artifacts:"
      - pwd
      - echo "Listing files in current directory:"
      - ls -la      
artifacts:
  files:
    - imageDetail.json
  name: artifacts.zip
  discard-paths: yes
