version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$ECR_REPO_URL
      - IMAGE_TAG=latest
      - echo "Current directory:"
      - pwd
      - echo "Listing files in current directory:"
      - ls -la
      - echo "Listing files in EFS mount:"
      - ls -la $ABSOLUTE_PATH
      - echo "Copying repository from EFS..."
      - cp -r $ABSOLUTE_PATH .
      - echo "Listing files after copy:"
      - ls -la
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_URL:$IMAGE_TAG --build-arg PORT=$PORT --build-arg ENTRY_POINT=$ENTRY_POINT -f Dockerfile .
      - docker tag $ECR_REPO_URL:$IMAGE_TAG $ECR_REPO_URL:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $ECR_REPO_URL:latest
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' "$ECR_REPO_URL:$IMAGE_TAG" > imageDetail.json
      - cat imageDetail.json
      
artifacts:
  files:
    - imageDetail.json
  name: artifacts.zip
  discard-paths: yes
