name: "CI/CD: ECR Build & Ansible Deploy"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPO_URL: ${{secrets.ECR_REPO_URL}}
      IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # -- DOCKER BUILD AND PUSH TO ECR --

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin $ECR_REPO_URL

    - name: Build and Push Docker Image
      run: |
        docker build -t easy-deploy-backend app/
        docker tag easy-deploy-backend:latest $ECR_REPO_URL:$IMAGE_TAG
        docker push $ECR_REPO_URL:$IMAGE_TAG
    # allow ecs to force pull latest image
    - name: Update ECS Service
      run: |
        aws ecs update-service \
          --cluster ecs-cluster \
          --service ecs-service \
          --force-new-deployment 
