---
- name: Install Python 3.8
  hosts: webserver
  become: yes
  gather_facts: no

  tasks:
    - name: Configure Amazon Linux 2 repository
      raw: |
        amazon-linux-extras enable python3.8
        yum clean all

    - name: Install required packages
      raw: |
        yum update -y
        yum install -y python3.8 python3.8-devel python3.8-pip gcc openssl-devel bzip2-devel libffi-devel xz-devel wget

    - name: Create symlinks and update PATH
      raw: |
        ln -sf /usr/bin/python3.8 /usr/bin/python3
        ln -sf /usr/bin/pip3.8 /usr/bin/pip3
        echo 'export PATH="/usr/local/bin:$PATH"' >> /etc/profile.d/python3.8.sh
        chmod +x /etc/profile.d/python3.8.sh
        source /etc/profile.d/python3.8.sh

    - name: Upgrade pip
      raw: |
        /usr/bin/pip3.8 install --upgrade pip 